sudo: required
services:
  - docker 

before_install:
  - docker build -t lohithmm/docker-react-ui -f Dockerfile.dev .

script: 
  -  docker run -e CI=true lohithmm/docker-react-ui  npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-ui"
  env: "DockerReactUi-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-124736381087"
  bucket_path: "docker-react-ui"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    
     
